version: '3.8'

services:
  api:
    build: 
      context: .
      dockerfile: Dockerfile.prod
    restart: always
    environment:
      - GIN_MODE=release
      - DB_HOST=db
      - DB_NAME=stockify
      # - DB_PORT=3306
      - DB_USERNAME=aungpao
      - DB_PASSWORD=1234

    ports:
      - 8082:8082
    depends_on:
      - db

  db:
    image: mysql:8.0.33
    restart: always
    environment:
      MYSQL_DATABASE: stockify
      MYSQL_USER: aungpao
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_PASSWORD: Supawat123159147
    volumes:
      - stockify_data:/var/lib/mysql

volumes:
  stockify_data:
