version: '3.8'

services:
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env.dev
    environment:
      - GIN_MODE=debug
      - DB_HOST=db
      - DB_NAME=stockify

    ports:
      - 8082:8082
    depends_on:
      - db

  db:
    image: mysql:8.0.33
    restart: always
    env_file:
      - .env.dev
    environment:
      MYSQL_DATABASE: stockify

    volumes:
      - stockify_data:/var/lib/mysql

volumes:
  stockify_data:
